### ISSUE TITLE
[Question] > Could not read script ... rubyUtils.gradle as it does not exist.

### ISSUE THREAD

**Issue by liangyuanpeng** [logstash-plugins/logstash-codec-java_codec_example#5]
I just got the err when i run 
```
gradlew.bat assemble
```

And [https://www.elastic.co/guide/en/logstash/6.6/java-filter-plugin.html#_set_up_your_environment_2](https://www.elastic.co/guide/en/logstash/6.6/java-filter-plugin.html#_set_up_your_environment_2)  No declaration of rubyUtils.gradle , 

so, what can i do for it? 

thank any help!!

**Comment by danhermann** [comment]
The `rubyUtils.gradle` file is in the Logstash repository. If you follow the instructions in the "Set up your environment" section, it tells you how to obtain a local copy of the Logstash repo and how to edit your `gradle.properties` file to specify the location of your local copy of the Logstash repo. Once you've done that, the `rubyUtils.gradle` file will be found and all the Gradle build targets should function properly.

On an related note, I would encourage you to upgrade from Logstash 6.6 if that's what you're currently using because Java plugin support was only experimental in that release and many improvements were made to it in later releases.
